<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>0152b813-eb4d-467a-be5f-bf5e40d81d71</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MediatR" Version="14.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ToDoList.Domain\ToDoList.Domain.csproj" />
      <ProjectReference Include="..\ToDoList.Infrastructure\ToDoList.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Rooms\Command\" />
      <Folder Include="Features\Rooms\Queries\" />
    </ItemGroup>

</Project>
